- name: Maven Package and Deploy
  hosts: localhost
  connection: local
  become: true
  become_user: root
  become_pass: intelintel
  tasks:
    - name: 'source code : local install'
      command: mvn  clean package
