- name: Maven Package and Deploy
  hosts: localhost
  connection: local
  vars_files:
   - /home/sabareesan/secret
  tasks:
    - name: 'source code : local install'
      command: mvn  clean package
      become: true
      become_user: sabareesan
